image: node:latest

stages:
    - deploy

deploy:
    stage: deploy
    image: ruby:latest
    variables:
        HEROKU_STAGING_API_KEY: $HEROKU_API_KEY
        HEROKU_STAGING_APP: $HEROKU_APP_NAME
    tags:
        - ugrad
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y && apt-get intall ruby-dev -y)'
        - eval $(ssh-agent -s)   
    script:
        - export PATH=$PATH:/home/gitlab-runner/.gem/ruby/2.5.0/bin
        - gem install dpl --user-install -- verbose
        - gem install faraday -v 0.9.2 --user-install
        - gem install netrc -v 0.11.0 --user-install
        - gem install rendezvous -v 0.1.3 --user-install
        - eval 'dpl heroku api --app "$HEROKU_STAGING_APP" --api_key "$HEROKU_STAGING_API_KEY"'
    only:
        - main
